# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae2947c5dbf078aa58cc684cab1bb751557a5b7382be744f8e8e1f07c2d1e95d767ea2acd763ffb5f812adefb923ed90e7ecc45b51a74ebc15a8053994f8e77f

test:
  secret_key_base: 0ccfc96b4c0bf21d09245c97c451af7d898a5b4aa1e1bfd6e8872a50707810bbab4e757510c8e041edbf984e69e879165825d3496d7bd414aa7a6798eaee9308

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
